Repository jobseek/speedjobs, pull requests merged in 2021-04, with the labels that each got.

#5 feat: 깃헙 로그인
  front/src/components/components/Modal/Sns.js
  src/main/java/com/jobseek/speedjobs/common/exception/OAuth2RegistrationException.java
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/config/WebConfig.java
  src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/dto/auth/TokenRequest.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
Labels: back

#10 Refactor: 소셜 로그인 리팩토링
  front/package-lock.json
  front/src/components/components/Modal/Sns.js
  src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/domain/user/Provider.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserRepository.java
  src/main/java/com/jobseek/speedjobs/dto/auth/TokenRequest.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
Labels: back

#11 feat: 네이버 로그인
  front/package-lock.json
  front/package.json
  front/src/components/components/Modal/Sns.js
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
Labels: back

#12 feat: 로그인 시 새로고침 문제 해결
  front/src/App.js
  front/src/auth/interceptor.js
  front/src/components/components/Chatting/ChatBox.js
  front/src/components/components/Modal/Sns.js
  front/src/components/components/NavDrop.js
  front/src/components/components/NavMenu.js
  front/src/components/components/Notification/PopUp.js
  front/src/components/components/Styled.js
  front/src/components/includes/Header.js
  front/src/components/pages/Community.js
  front/src/components/pages/PostAdd.js
  front/src/components/pages/Profile.js
  front/src/reducers/user.js
  front/src/sagas/user.js
Labels: front

#14 feat: 게시물 CRUD 기능 추가(테스트용)
  build.gradle
  front/package-lock.json
  front/yarn.lock
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/controller/AuthController.java
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostRepository.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Active.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java
  src/main/java/com/jobseek/speedjobs/dto/auth/TokenRequest.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostListDto.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostResponseDto.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSaveDto.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostUpdateDto.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/test/java/com/jobseek/speedjobs/SpeedjobsApplicationTest.java
  src/test/java/com/jobseek/speedjobs/common/BaseTest.java
  src/test/java/com/jobseek/speedjobs/domain/post/PostRepositoryTest.java
Labels: back

#15 fix: 로그인 두번 되는 현상 해결
  front/package-lock.json
  front/package.json
  front/src/App.css
  front/src/App.js
  front/src/auth/interceptor.js
  front/src/components/components/Modal/Sns.js
  front/src/components/components/Post.js
  front/src/components/data/useFetch.js
  front/src/components/pages/Community.js
  front/src/components/pages/PostAdd.js
  front/src/components/pages/PostDetail.js
  front/src/reducers/index.js
  front/src/reducers/post.js
  front/src/sagas/index.js
  front/src/sagas/post.js
  front/src/sagas/user.js
Labels: front

#18 feat: 유저, 이력서 관련 엔티티 생성
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/member/MemberRepository.java
  src/main/java/com/jobseek/speedjobs/domain/member/MemberService.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Career.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Certificate.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Scholar.java
  src/main/java/com/jobseek/speedjobs/domain/user/Role.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/test/java/com/jobseek/speedjobs/domain/member/MemberTest.java
Labels: back

#19 feat: Domain 추가본
  src/main/java/com/jobseek/speedjobs/domain/corporation/Corporation.java
  src/main/java/com/jobseek/speedjobs/domain/corporation/CorporationDetail.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostDetail.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Experience.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Position.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitDetail.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Status.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Career.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Certificate.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Scholar.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostResponseDto.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSaveDto.java
Labels: back

#21 feat: 회원가입 데이터 확인 추가
  front/src/App.js
  front/src/auth/interceptor.js
  front/src/components/components/Banner.js
  front/src/components/components/Chatting/ChatBox.js
  front/src/components/components/Modal/InputLine.js
  front/src/components/components/Modal/SignUp.js
  front/src/components/components/NavDrop.js
  front/src/components/components/NavSearch.js
  front/src/components/components/Notification/PopUp.js
  front/src/components/components/Search/SearchArea.js
  front/src/components/components/Styled.js
  front/src/components/components/Tags.js
  front/src/components/components/comment/PostDetailComment.js
  front/src/components/components/img/img.jpeg
  front/src/components/components/img/img22.png
  front/src/components/data/hangul.js
  front/src/components/data/signUpCheck.js
  front/src/components/includes/Header.js
  front/src/components/includes/ScrollToTop.js
  front/src/components/pages/CommuLike.js
  front/src/components/pages/Community.js
  front/src/components/pages/Home.js
  front/src/components/pages/PostAdd.js
  front/src/components/pages/PostDetail.js
  front/src/components/pages/Profile.js
  front/src/components/pages/RecruitAdd.js
  front/src/components/pages/Recruitment.js
  front/src/components/pages/RecruitmentDetail.js
  front/src/reducers/post.js
  front/src/reducers/user.js
  front/src/sagas/post.js
  front/src/sagas/user.js
  src/main/java/com/jobseek/speedjobs/controller/AuthController.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
Labels: bug, front

#22 feat: 이메일 인증 구현
  build.gradle
  front/package-lock.json
  front/yarn.lock
  src/main/java/com/jobseek/speedjobs/common/exception/InvalidEntityException.java
  src/main/java/com/jobseek/speedjobs/config/RedisConfig.java
  src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/company/CompanyDetail.java
  src/main/java/com/jobseek/speedjobs/domain/corporation/CorporationDetail.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/user/Role.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/utils/MailUtil.java
  src/main/java/com/jobseek/speedjobs/utils/RedisUtil.java
  src/main/resources/templates/email.html
Labels: back

#27 feat: domain 남은 부분 Mapping Complete
  .gitignore
  src/main/java/com/jobseek/speedjobs/common/ResultResponse.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/company/CompanyDetail.java
  src/main/java/com/jobseek/speedjobs/domain/likelist/CompanyLikeList.java
  src/main/java/com/jobseek/speedjobs/domain/likelist/PostLikeList.java
  src/main/java/com/jobseek/speedjobs/domain/likelist/RecruitLikeList.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/message/Message.java
  src/main/java/com/jobseek/speedjobs/domain/post/Comment.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostDetail.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitDetail.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Apply.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Career.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Open.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Scholar.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Career.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Certificate.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Scholar.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/School.java
  src/main/java/com/jobseek/speedjobs/domain/tag/BoardTag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/RecruitTags.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Type.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserInfoResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserTokenDto.java
Labels: back

#28 fix: 기업회원 회원가입 수정, 소셜 로그인 멤버 추가
  build.gradle
  front/yarn.lock
  src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostDetail.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/auth/TokenRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/utils/RedisUtil.java
Labels: back

#29 feat: User Update api 추가
  build.gradle
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/member/MemberUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/http/User.http
Labels: back

#31 feat: S3 연동 및 배너 추가
  build.gradle
  front/src/sagas/post.js
  front/yarn.lock
  src/main/java/com/jobseek/speedjobs/controller/AuthController.java
  src/main/java/com/jobseek/speedjobs/controller/BannerController.java
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/banner/Banner.java
  src/main/java/com/jobseek/speedjobs/domain/banner/BannerRepository.java
  src/main/java/com/jobseek/speedjobs/dto/banner/BannerResponse.java
  src/main/java/com/jobseek/speedjobs/dto/banner/BannerResponses.java
  src/main/java/com/jobseek/speedjobs/service/BannerService.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/utils/S3Util.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/test/java/com/jobseek/speedjobs/domain/post/PostRepositoryTest.java
Labels: back

#36 feat: admin 페이지 추가
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/admin/component/InfoCard.js
  front/src/components/admin/component/Input.js
  front/src/components/admin/component/Report.js
  front/src/components/admin/component/SideBar.js
  front/src/components/admin/component/adminStyled.js
  front/src/components/admin/data/UserChart.js
  front/src/components/admin/page/AdminHome.js
  front/src/components/admin/page/Login.js
  front/src/components/components/Profile/ProfileContents.js
  front/src/components/components/Registration/RegisterContents.js
  front/src/components/components/resume/ResumeCareer.js
  front/src/components/components/resume/ResumeCertificate.js
  front/src/components/components/resume/ResumeContents.js
  front/src/components/components/resume/ResumeSkill.js
  front/src/components/pages/Profile.js
  front/src/components/pages/RecruitAdd.js
  front/src/components/pages/Recruitment.js
  src/main/resources/application.properties
Labels: front

#37 feat: 개인정보 이미지 업로드 기능
  front/src/components/components/Profile/ProfileContents.js
  front/src/components/components/Profile/ProfileGender.js
  front/src/components/components/Profile/ProfileImage2.js
  front/src/components/components/Styled.js
  front/src/components/components/resume/ResumeBasic.js
  front/src/components/pages/Profile.js
Labels: front

#39 feat: 개인&기업회원 회원가입 수정
  front/package-lock.json
  front/package.json
  front/src/components/components/comment/Comment.js
  front/src/components/components/comment/PostDetailComment.js
  front/src/components/includes/Header.js
  front/src/components/pages/Community.js
  front/src/components/pages/PostAdd.js
  front/src/components/pages/PostDetail.js
  front/src/reducers/comment.js
  front/src/sagas/comment.js
  front/src/sagas/user.js
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserCheckRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserValidateGroup.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyInfoResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/member/MemberInfoResponse.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/application.properties
Labels: back

#40 feat: 게시물, 태그
  .gitattributes
  build.gradle
  front/package-lock.json
  front/package.json
  front/yarn.lock
  src/main/java/com/jobseek/speedjobs/InitDb.java
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
  src/main/java/com/jobseek/speedjobs/controller/TagController.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/likelist/CompanyLikeList.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitDetail.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java
  src/main/java/com/jobseek/speedjobs/domain/tag/BoardTag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTagRepository.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/TagRepository.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSaveDto.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagResponses.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagSaveRequest.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/http/Post.http
  src/main/resources/http/User.http
  src/test/java/com/jobseek/speedjobs/domain/member/MemberTest.java
  src/test/java/com/jobseek/speedjobs/domain/tag/TagRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java
  src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java
Labels: back

#41 feat: 태그, 게시물 보충
  src/main/java/com/jobseek/speedjobs/controller/TagController.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSaveDto.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagResponses.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
Labels: back

#47 feat: 게시물, 태그 연동
  front/yarn.lock
  src/main/java/com/jobseek/speedjobs/InitDb.java
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/config/SwaggerConfig.java
  src/main/java/com/jobseek/speedjobs/controller/BannerController.java
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/controller/TagController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/likelist/CompanyLike.java
  src/main/java/com/jobseek/speedjobs/domain/likelist/PostLike.java
  src/main/java/com/jobseek/speedjobs/domain/likelist/RecruitLike.java
  src/main/java/com/jobseek/speedjobs/domain/post/Comment.java
  src/main/java/com/jobseek/speedjobs/domain/post/CommentRepository.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTagRepository.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTags.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/post/CommentRequest.java
  src/main/java/com/jobseek/speedjobs/dto/post/CommentResponse.java
  src/main/java/com/jobseek/speedjobs/dto/post/CommentResponses.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostListDto.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostRequest.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostResponse.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostResponseDto.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSaveDto.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostUpdateDto.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagResponses.java
  src/main/java/com/jobseek/speedjobs/service/CommentService.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
Labels: back

#61 feat: 개인정보 수정 기능 추가
  front/src/App.js
  front/src/components/components/Profile/ProfileDetails.js
  front/src/components/components/Profile/ProfileImage.js
  front/src/components/components/Profile/ProfileInputTel.js
  front/src/components/components/Profile/ProfileInputs.js
  front/src/components/components/Profile/ProfileModify.js
  front/src/components/components/Profile/ProfileTextarea.js
  front/src/components/components/Styled.js
  front/src/components/components/resume/ResumeBasic.js
  front/src/components/components/resume/ResumeCareer.js
  front/src/components/components/resume/ResumeCertificate.js
  front/src/components/pages/Community.js
  front/src/components/pages/Profile.js
  front/src/components/pages/ProfileMd.js
  front/src/reducers/profile.js
  front/src/sagas/profile.js
  src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserInfoResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/member/MemberInfoResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/member/MemberUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/http/user.http
Labels: back, bug, front

#68 feat: 태그 관계 수정 및 기업회원 정보 수정 기능 추가
  src/main/java/com/jobseek/speedjobs/config/SwaggerConfig.java
  src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
  src/main/java/com/jobseek/speedjobs/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/jobseek/speedjobs/controller/BannerController.java
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
  src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/company/CompanyDetail.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTagRepository.java
  src/main/java/com/jobseek/speedjobs/domain/tag/PostTags.java
  src/main/java/com/jobseek/speedjobs/domain/tag/RecruitTag.java
  src/main/java/com/jobseek/speedjobs/domain/tag/RecruitTagRepository.java
  src/main/java/com/jobseek/speedjobs/domain/tag/RecruitTags.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/dto/post/CommentResponse.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostListResponse.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitListResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyInfoResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/BannerService.java
  src/main/java/com/jobseek/speedjobs/service/CommentService.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/ResumeService.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/http/post.http
  src/main/resources/http/recruit.http
  src/main/resources/http/resume.http
  src/test/java/com/jobseek/speedjobs/service/BannerServiceTest.java
  src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java
Labels: back

#74 feat: 게시글 검색 기능 추가
  build.gradle
  front/src/sagas/recruit.js
  src/main/java/com/jobseek/speedjobs/config/QuerydslConfig.java
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostListResponse.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/utils/QueryDslUtil.java
  src/main/resources/http/post.http
  src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java
Labels: back

#75 feat: 기업회원 수락 페이지 추가
  front/README.md
  front/src/App.js
  front/src/auth/interceptor.js
  front/src/components/admin/component/CompanyInfo.js
  front/src/components/admin/component/SideBar.js
  front/src/components/admin/component/TagList.js
  front/src/components/admin/page/AdminHome.js
  front/src/components/admin/page/AdminMain.js
  front/src/components/admin/page/BannerSetting.js
  front/src/components/admin/page/CompanySetting.js
  front/src/components/components/RecruitAdd/AnnounceLocation.js
  front/src/components/components/Styled.js
  front/src/components/components/comment/Comment.js
  front/src/components/data/KakaoMap.js
  front/src/components/pages/PostDetail.js
  front/src/components/pages/RecruitmentDetail.js
  front/src/reducers/user.js
  front/src/sagas/user.js
Labels: bug, front

#77 feat: 회원 탈퇴 기능 추가
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserCheckRequest.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/http/post.http
  src/main/resources/http/user.http
  src/test/java/com/jobseek/speedjobs/domain/post/PostRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java
  src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java
Labels: back

#78 feat: 검색기능구현
  front/src/auth/interceptor.js
  front/src/components/components/Nav/NavSearch.js
  front/src/components/components/Search/SearchArea.js
  front/src/components/pages/ProfileMd.js
  front/src/components/pages/ProfileMd2.js
Labels: front

#80 feat: 공고 검색/페이징/정렬 추가(Todo 날짜별, Enum), 이력서 수정
  src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
  src/main/java/com/jobseek/speedjobs/domain/company/CompanyDetail.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostListResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitRequest.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeRequest.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/ResumeService.java
  src/main/java/com/jobseek/speedjobs/utils/QueryDslUtil.java
  src/main/resources/data.sql
  src/main/resources/http/post.http
  src/main/resources/http/recruit.http
  src/main/resources/http/resume.http
  src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java
Labels: back, bug

#82 feat: 댓글 추천 기능 추가
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/post/Comment.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/post/CommentResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/service/CommentService.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/resources/data.sql
  src/main/resources/http/post.http
Labels: back

#84 feat: 공고 검색추가
  front/src/components/components/Search/SearchArea.js
  front/src/components/pages/Community.js
  front/src/components/pages/Recruitment.js
  front/src/reducers/post.js
  front/src/reducers/recruit.js
  front/src/sagas/post.js
  front/src/sagas/recruit.js
Labels: front

#85 fix: 게시글, 공고 검색 수정
  src/main/java/com/jobseek/speedjobs/config/SwaggerConfig.java
  src/main/java/com/jobseek/speedjobs/controller/FileController.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/resources/http/post.http
  src/main/resources/http/recruit.http
Labels: back

#86 feat: 공고 세부 검색 기능 추가
  front/src/components/pages/RecruitAdd.js
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Experience.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitDetail.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Status.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitListResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitRequest.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/utils/CookieUtil.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/data.sql
  src/main/resources/http/recruit.http
Labels: back

#87 fix: 태그 컴포넌트 분리, styledHeader 레이아웃변경
  front/src/components/components/Styled.js
  front/src/components/components/Tags.js
  front/src/components/components/banner/Banner.js
  front/src/components/components/banner/BannerImg.js
  front/src/components/components/img/banner.jpg
  front/src/components/components/img/banners/img.jpeg
  front/src/components/components/img/banners/img.png
  front/src/components/components/img/banners/img2.jpeg
  front/src/components/components/img/banners/img2.png
  front/src/components/components/img/banners/img3.jpeg
  front/src/components/components/tag/TagSelector.js
  front/src/components/components/tag/TagShower.js
  front/src/components/pages/Community.js
  front/src/components/pages/PostDetail.js
  front/src/components/pages/Profile2.js
  front/src/components/pages/Recruitment.js
  front/src/components/pages/RecruitmentDetail.js
  front/src/components/pages/home/AnnounceCard.js
Labels: front

#88 feat: 회원 조회 및 공고 스케쥴링
  front/src/components/components/Registration/RegisterContents.js
  src/main/java/com/jobseek/speedjobs/config/ScheduledConfig.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Career.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Certificate.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Scholar.java
  src/main/java/com/jobseek/speedjobs/domain/user/Role.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserRepository.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserListResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSearchCondition.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/utils/MailUtil.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/http/user.http
  src/main/resources/templates/email.html
  src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java
Labels: back
