Repository jobseek/speedjobs, pull requests merged in 2021-05, with the labels that each got.

#89 feat: 캐시 적용
  src/main/java/com/jobseek/speedjobs/SpeedjobsApplication.java
  src/main/java/com/jobseek/speedjobs/config/ScheduledConfig.java
  src/main/java/com/jobseek/speedjobs/config/SwaggerConfig.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagResponses.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
  src/main/resources/http/tag.http
Labels: back

#90 feat: Advice & AOP 적용
  build.gradle
  src/main/java/com/jobseek/speedjobs/advice/RestExceptionHandler.java
  src/main/java/com/jobseek/speedjobs/advice/dto/ResultResponse.java
  src/main/java/com/jobseek/speedjobs/aop/ControllerLoggingAspect.java
  src/main/java/com/jobseek/speedjobs/aop/ServiceLoggingAspect.java
  src/main/java/com/jobseek/speedjobs/common/ErrorCode.java
  src/main/java/com/jobseek/speedjobs/common/exception/DuplicatedException.java
  src/main/java/com/jobseek/speedjobs/common/exception/InvalidEntityException.java
  src/main/java/com/jobseek/speedjobs/common/exception/InvalidTokenException.java
  src/main/java/com/jobseek/speedjobs/common/exception/NotExistException.java
  src/main/java/com/jobseek/speedjobs/common/exception/NotFoundException.java
  src/main/java/com/jobseek/speedjobs/common/exception/OAuth2RegistrationException.java
  src/main/java/com/jobseek/speedjobs/common/exception/UnAuthorizedException.java
  src/main/java/com/jobseek/speedjobs/common/exception/UnMatchedException.java
  src/main/java/com/jobseek/speedjobs/common/exception/UnauthorizedException.java
  src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
  src/main/java/com/jobseek/speedjobs/domain/post/Comment.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/domain/user/exception/InvalidTokenException.java
  src/main/java/com/jobseek/speedjobs/domain/user/exception/NotFoundKeyException.java
  src/main/java/com/jobseek/speedjobs/domain/user/exception/NotFoundOAuth2Exception.java
  src/main/java/com/jobseek/speedjobs/domain/user/exception/NotFoundRoleException.java
  src/main/java/com/jobseek/speedjobs/domain/user/exception/OAuth2RegistrationException.java
  src/main/java/com/jobseek/speedjobs/domain/user/exception/SignUpRuleException.java
  src/main/java/com/jobseek/speedjobs/domain/user/exception/WrongPasswordException.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
  src/main/java/com/jobseek/speedjobs/service/BannerService.java
  src/main/java/com/jobseek/speedjobs/service/CommentService.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/ResumeService.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/utils/S3Util.java
  src/main/resources/http/admin.http
  src/main/resources/http/post.http
  src/main/resources/http/user.http
Labels: back

#93 refactor: 회원 로직 리팩토링 및 코드 정리
  src/main/java/com/jobseek/speedjobs/SpeedjobsApplication.java
  src/main/java/com/jobseek/speedjobs/common/ResultResponse.java
  src/main/java/com/jobseek/speedjobs/config/AppConfig.java
  src/main/java/com/jobseek/speedjobs/config/JpaConfig.java
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/domain/banner/Banner.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/company/CompanyDetail.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/message/Message.java
  src/main/java/com/jobseek/speedjobs/domain/post/Comment.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostDetail.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitDetail.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Apply.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserDto.java
  src/main/java/com/jobseek/speedjobs/dto/user/member/MemberUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/utils/JwtUtil.java
  src/main/java/com/jobseek/speedjobs/utils/MailUtil.java
  src/test/java/MvcTest.java
Labels: back

#96 feat: 테스트 시큐리티 및 에러코드 추가
  front/src/components/components/resume/.ResumeBasic.js.swp
  src/main/java/com/jobseek/speedjobs/advice/RestExceptionHandler.java
  src/main/java/com/jobseek/speedjobs/advice/dto/ValidResponse.java
  src/main/java/com/jobseek/speedjobs/common/ErrorCode.java
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/domain/banner/Banner.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Career.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Certificate.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Scholar.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitRequest.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/ResumeService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/utils/QueryDslUtil.java
  src/main/resources/data.sql
  src/main/resources/http/post.http
  src/main/resources/http/recruit.http
  src/main/resources/http/resume.http
  src/main/resources/http/tag.http
  src/main/resources/http/user.http
  src/test/java/com/jobseek/speedjobs/domain/banner/BannerRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/domain/post/PostRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/domain/resume/ResumeTest.java
  src/test/java/com/jobseek/speedjobs/domain/tag/TagRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/domain/user/UserTest.java
  src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java
Labels: back

#97 fix: 로그아웃 로직 변경
  front/src/auth/interceptor.js
  front/src/components/admin/component/AdminAlert.js
  front/src/components/admin/component/Input.js
  front/src/components/admin/component/SideBar.js
  front/src/components/admin/component/TagList.js
  front/src/components/admin/component/adminStyled.js
  front/src/components/admin/page/AdminHome.js
  front/src/components/admin/page/Login.js
  front/src/components/components/Post/PostList.js
  front/src/components/components/Styled.js
  front/src/components/components/banner/Banner.js
  front/src/components/components/img/banners/Img3.jpeg
  front/src/components/components/img/banners/Img4.jpeg
  front/src/components/includes/Header.js
  front/src/components/pages/PostDetail.js
  front/src/reducers/admin.js
  front/src/reducers/index.js
  front/src/reducers/user.js
  front/src/sagas/admin.js
  front/src/sagas/index.js
  front/src/sagas/user.js
Labels: front

#99 feat: 이력서 태그/검색, 지원 조회, DB 예외 추가
  src/main/java/com/jobseek/speedjobs/advice/RestExceptionHandler.java
  src/main/java/com/jobseek/speedjobs/common/ErrorCode.java
  src/main/java/com/jobseek/speedjobs/controller/ApplyController.java
  src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
  src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Apply.java
  src/main/java/com/jobseek/speedjobs/domain/resume/ApplyRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/resume/ResumeQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/ResumeTag.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserRepository.java
  src/main/java/com/jobseek/speedjobs/dto/apply/CompanyResponse.java
  src/main/java/com/jobseek/speedjobs/dto/apply/MemberResponse.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeRequest.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeSearchCondition.java
  src/main/java/com/jobseek/speedjobs/service/ApplyService.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/ResumeService.java
  src/main/resources/data.sql
  src/main/resources/http/apply.http
  src/main/resources/http/recruit.http
  src/main/resources/http/resume.http
  src/test/java/com/jobseek/speedjobs/domain/resume/ResumeTest.java
  src/test/java/com/jobseek/speedjobs/service/ResumeServiceTest.java
Labels: back

#102 feat: admin UserListResponse 데이터 추가
  src/main/java/com/jobseek/speedjobs/dto/user/UserListResponse.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/http/admin.http
Labels: back

#103 feat: 채팅 기능 추가
  build.gradle
  front/src/components/components/Styled.js
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/config/WebSocketConfig.java
  src/main/java/com/jobseek/speedjobs/controller/AuthController.java
  src/main/java/com/jobseek/speedjobs/controller/ChatController.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/message/Message.java
  src/main/java/com/jobseek/speedjobs/domain/message/MessageRepository.java
  src/main/java/com/jobseek/speedjobs/domain/post/Comment.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitDetail.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/Certificate.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/message/MessageRequest.java
  src/main/java/com/jobseek/speedjobs/dto/message/MessageResponse.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
  src/main/java/com/jobseek/speedjobs/service/ChatService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/utils/MailUtil.java
  src/main/resources/http/admin.http
  src/main/resources/http/banner.http
  src/main/resources/http/post.http
  src/main/resources/http/recruit.http
  src/main/resources/http/resume.http
  src/main/resources/http/tag.http
  src/main/resources/http/user.http
  src/test/java/com/jobseek/speedjobs/controller/UserControllerTest.java
  src/test/java/com/jobseek/speedjobs/domain/post/PostQueryRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/domain/user/UserTest.java
  src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java
  src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java
Labels: back

#104 feat: 채팅 일부기능추가, 로그인 수정
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/auth/address.js
  front/src/auth/interceptor.js
  front/src/components/admin/data/UserChart.js
  front/src/components/components/Chatting/ChatBox.js
  front/src/components/components/Styled.js
  front/src/sagas/user.js
Labels: front

#106 feat: sonarqube 추가
  .gitignore
  build.gradle
  front/package-lock.json
  front/src/components/admin/page/Login.js
  front/src/sagas/user.js
  gradlew
  src/main/java/com/jobseek/speedjobs/common/exception/UnauthorizedException.java
  src/main/resources/http/banner.http
Labels: back

#110 feat: 공고에 이력서 지원하기 추가
  front/src/components/components/Modal/Modal.js
  front/src/components/components/Nav/NavDrop.js
  front/src/components/components/Nav/NavMenu.js
  front/src/components/components/Post/PostList.js
  front/src/components/components/Registration/RegisterInput.js
  front/src/components/components/SubmitItem.js
  front/src/components/data/mapLink.js
  front/src/components/pages/MyRecruitments.js
  front/src/components/pages/RecruitmentDetail.js
  front/src/components/pages/SubmitList.js
  front/src/reducers/company.js
  front/src/reducers/resume.js
  front/src/sagas/company.js
  front/src/sagas/resume.js
  src/main/java/com/jobseek/speedjobs/advice/RestExceptionHandler.java
  src/main/java/com/jobseek/speedjobs/config/auth/exception/ExpiredTokenException.java
  src/main/java/com/jobseek/speedjobs/config/auth/exception/InvalidTokenException.java
  src/main/resources/http/apply.http
Labels: front

#112 fix: 이력서 수정, 태그 추가
  src/main/java/com/jobseek/speedjobs/SpeedjobsApplication.java
  src/main/java/com/jobseek/speedjobs/advice/dto/ValidResponse.java
  src/main/java/com/jobseek/speedjobs/config/QuerydslConfig.java
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/controller/ChatController.java
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
  src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Apply.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/domain/resume/ResumeQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/details/ResumeTag.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserRepository.java
  src/main/java/com/jobseek/speedjobs/dto/banner/BannerResponse.java
  src/main/java/com/jobseek/speedjobs/dto/banner/BannerResponses.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeRequest.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeResponse.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
  src/main/java/com/jobseek/speedjobs/service/PostService.java
  src/main/java/com/jobseek/speedjobs/service/ResumeService.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
  src/main/resources/data.sql
  src/main/resources/http/resume.http
  src/test/java/com/jobseek/speedjobs/domain/resume/ResumeTest.java
Labels: back

#113 fix: 컨트롤러 권한 변경
  build.gradle
  front/src/components/components/banner/Banner.js
  front/src/components/data/registerCheck.js
  front/src/components/data/signUpCheck.js
  front/src/components/pages/profile/Withdrawal.js
  src/main/java/com/jobseek/speedjobs/advice/RestExceptionHandler.java
  src/main/java/com/jobseek/speedjobs/controller/ApplyController.java
  src/main/java/com/jobseek/speedjobs/controller/ChatController.java
  src/main/java/com/jobseek/speedjobs/controller/PostController.java
  src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
  src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
  src/main/java/com/jobseek/speedjobs/controller/TagController.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/message/Message.java
  src/main/java/com/jobseek/speedjobs/domain/post/Comment.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeRequest.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSearchCondition.java
  src/main/java/com/jobseek/speedjobs/service/ApplyService.java
  src/main/java/com/jobseek/speedjobs/service/CommentService.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/ResumeService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/http/admin.http
  src/main/resources/http/apply.http
  src/main/resources/http/post.http
  src/main/resources/http/recruit.http
  src/test/java/com/jobseek/speedjobs/domain/post/PostQueryRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepositoryTest.java
  src/test/java/com/jobseek/speedjobs/domain/resume/ResumeTest.java
Labels: back

#116 feat: 게시글, 공고 조회 조건 추가
  src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java
Labels: back

#120 fix: 서버 url 수정
  front/.gitignore
  front/public/email.html
  front/src/auth/address.js
  front/src/auth/interceptor.js
  front/src/components/components/Chatting/ChatBox.js
  front/src/components/components/Modal/Sns.js
  front/src/components/components/Profile/CorporateDetails.js
  front/src/components/components/Profile/IndividualDetails.js
  front/src/components/components/Profile/ProfileImage.js
  front/src/components/components/comment/Comment.js
  front/src/components/components/resume/ResumeBasic.js
  front/src/components/pages/ResumeDetails.js
  front/src/components/pages/home/AnnounceCard.js
  front/src/components/pages/profile/CorporateModify.js
  front/src/components/pages/profile/IndividualModify.js
  front/src/sagas/index.js
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/company/CompanyQueryRepository.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/resources/http/user.http
Labels: back, front, infra

#121 feat: 태그 테스트 추가, 백엔드 쿠키 삭제
  .gitignore
  front/.gitignore
  front/src/auth/address.js
  front/src/components/admin/component/Report.js
  front/src/components/components/Modal/Sns.js
  front/src/components/components/Nav/NavLink.js
  front/src/components/components/Nav/NavSearch.js
  front/src/components/components/NavSearch.js
  front/src/components/components/Notification/ModalAlert.js
  front/src/components/components/Post/PostList.js
  front/src/components/components/Profile/IndividualDetails.js
  front/src/components/components/Profile/ProfileTextarea.js
  front/src/components/components/animation/NavAnimation.js
  front/src/components/includes/Header.js
  front/src/components/pages/PostAdd.js
  front/src/components/pages/PostModify.js
  front/src/components/pages/RecruitmentDetail.js
  front/src/components/pages/ResumeModify.js
  front/src/components/pages/profile/CorporateModify.js
  front/src/components/pages/profile/Profile.js
  front/src/components/pages/profile/Withdrawal.js
  front/src/sagas/admin.js
  front/src/sagas/comment.js
  front/src/sagas/company.js
  front/src/sagas/like.js
  front/src/sagas/recruit.js
  front/src/sagas/resume.js
  src/main/java/com/jobseek/speedjobs/controller/ChatController.java
  src/main/java/com/jobseek/speedjobs/controller/TagController.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagRequest.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagResponses.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
  src/main/java/com/jobseek/speedjobs/utils/CookieUtil.java
  src/test/java/com/jobseek/speedjobs/controller/FileControllerTest.java
  src/test/java/com/jobseek/speedjobs/controller/UserControllerTest.java
  src/test/java/com/jobseek/speedjobs/domain/user/UserTest.java
  src/test/java/com/jobseek/speedjobs/service/RecruitServiceTest.java
  src/test/java/com/jobseek/speedjobs/service/ResumeServiceTest.java
  src/test/java/com/jobseek/speedjobs/service/TagServiceTest.java
Labels: back

#122 style: prettier 재적용
  front/src/components/components/Nav/NavLink.js
  front/src/components/components/Nav/NavSearch.js
  front/src/components/components/Notification/ModalAlert.js
  front/src/components/components/Post/PostList.js
  front/src/components/components/Profile/ProfileTextarea.js
  front/src/components/includes/Header.js
  front/src/components/pages/profile/CorporateModify.js
  front/src/components/pages/profile/Profile.js
  front/src/components/pages/profile/Withdrawal.js
  front/src/sagas/comment.js
  front/src/sagas/company.js
  front/src/sagas/recruit.js
  front/src/sagas/resume.js
  src/test/java/com/jobseek/speedjobs/service/TagServiceTest.java
Labels: front

#124 Feat: 공고 추가페이지 작성
  front/src/components/components/RecruitAdd/AnnounceLocation.js
  front/src/components/components/RecruitAdd/AnnouncementDate.js
  front/src/components/components/RecruitAdd/AnnouncementInfo.js
  front/src/components/components/RecruitAdd/CompanySummaryInfo.js
  front/src/components/components/RecruitAdd/RecruitAddContents.js
  front/src/components/components/Styled.js
  front/src/components/components/SubmitItem.js
  front/src/components/data/DaumAddress.js
  front/src/components/pages/RecruitAdd.js
  front/src/components/pages/Recruitment.js
  front/src/components/pages/RecruitmentDetail.js
  front/src/sagas/profile.js
  src/main/resources/http/post.http
  src/main/resources/http/recruit.http
Labels: front

#125 feat: 기업 정보 수정 및 검색 조건 추가
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/company/CompanyDetail.java
  src/main/java/com/jobseek/speedjobs/domain/post/Post.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/ResumeQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserQueryRepository.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostRequest.java
  src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserListResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyInfoResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java
Labels: back

#126 fix: 공고 상태 관리
  src/main/java/com/jobseek/speedjobs/advice/RestExceptionHandler.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/Status.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitListResponse.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitRequest.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitResponse.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/ResumeService.java
Labels: back

#127 feat: 메시지 삭제 기능 추가 및 소셜 로그인 로직 변경
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jobseek/speedjobs/controller/AuthController.java
  src/main/java/com/jobseek/speedjobs/controller/ChatController.java
  src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
  src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
  src/main/java/com/jobseek/speedjobs/domain/company/CompanyDetail.java
  src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyInfoResponse.java
  src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyUpdateRequest.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
  src/main/java/com/jobseek/speedjobs/service/ChatService.java
  src/main/resources/data.sql
  src/main/resources/http/user.http
Labels: back

#129 fix: 소셜로그인 방식변경
  front/src/App.js
  front/src/auth/interceptor.js
  front/src/components/components/Cards.js
  front/src/components/components/Post.js
  front/src/components/components/Styled.js
  front/src/components/components/Tags.js
  front/src/components/components/banner/Banner.js
  front/src/components/pages/Community.js
  front/src/components/pages/Home.js
  front/src/components/pages/NotFound.js
  front/src/components/pages/PostDetail.js
  front/src/components/pages/Recruitment.js
  front/src/components/pages/SocialLogin.js
  front/src/index.js
  front/src/reducers/user.js
  front/src/sagas/user.js
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
Labels: front

#130 feat: 공고 테스트 추가
  front/package-lock.json
  src/main/java/com/jobseek/speedjobs/domain/BaseTimeEntity.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/member/Member.java
  src/main/java/com/jobseek/speedjobs/domain/user/User.java
  src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitRequest.java
  src/main/java/com/jobseek/speedjobs/service/TagService.java
  src/test/java/com/jobseek/speedjobs/service/RecruitServiceTest.java
  src/test/java/com/jobseek/speedjobs/service/TagServiceTest.java
Labels: back

#131 feat: 공고수정 페이지 작성
  front/src/components/components/RecruitAdd/AnnouncementDate.js
  front/src/components/components/RecruitAdd/AnnouncementInfo.js
  front/src/components/components/RecruitAdd/CompanySummaryInfo.js
  front/src/components/components/RecruitAdd/RecruitAddContents.js
  front/src/components/pages/RecruitAdd.js
  front/src/components/pages/RecruitModify.js
  front/src/components/pages/Recruitment.js
  front/src/components/pages/RecruitmentDetail.js
  front/src/components/pages/ResumeDetails.js
  front/src/reducers/recruit.js
  front/src/sagas/recruit.js
  src/main/resources/http/recruit.http
Labels: front

#132 fix: 레이아웃조절
  front/src/components/components/Post.js
  front/src/components/components/Styled.js
  front/src/components/pages/PostDetail.js
  front/src/components/pages/RecruitmentDetail.js
Labels: front

#133 feat: 메일 이벤트 등록
  front/src/components/pages/RecruitmentDetail.js
  src/main/java/com/jobseek/speedjobs/config/AppConfig.java
  src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
  src/main/java/com/jobseek/speedjobs/config/auth/JwtAuthenticationFilter.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jobseek/speedjobs/controller/FileController.java
  src/main/java/com/jobseek/speedjobs/controller/UserController.java
  src/main/java/com/jobseek/speedjobs/domain/company/Company.java
  src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/ResumeQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserDto.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserQueryRepository.java
  src/main/java/com/jobseek/speedjobs/event/ApproveMailEvent.java
  src/main/java/com/jobseek/speedjobs/event/RegisterMailEvent.java
  src/main/java/com/jobseek/speedjobs/event/handler/MailEventHandler.java
  src/main/java/com/jobseek/speedjobs/service/AuthService.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
  src/main/java/com/jobseek/speedjobs/service/UserService.java
  src/main/java/com/jobseek/speedjobs/util/JwtUtil.java
  src/main/java/com/jobseek/speedjobs/util/MailUtil.java
  src/main/java/com/jobseek/speedjobs/util/QueryDslUtil.java
  src/main/java/com/jobseek/speedjobs/util/RedisUtil.java
  src/main/java/com/jobseek/speedjobs/util/S3Util.java
  src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java
Labels: back, front

#135 fix: 쿼리문 수정
  src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
  src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
  src/main/java/com/jobseek/speedjobs/domain/resume/ResumeQueryRepository.java
  src/main/java/com/jobseek/speedjobs/domain/user/UserQueryRepository.java
Labels: back

#138 feat: 공개이력서 목록 페이지 추가
  front/src/components/components/Chatting/ChatIcon.js
  front/src/components/components/ResumeItem.js
  front/src/components/components/SubmitItem.js
  front/src/components/pages/CommuLike.js
  front/src/components/pages/RecruitLike.js
  front/src/components/pages/Recruitment.js
  front/src/components/pages/RecruitmentDetail.js
  front/src/components/pages/SubmitList.js
  front/src/sagas/resume.js
  src/main/java/com/jobseek/speedjobs/dto/apply/MemberResponse.java
  src/main/java/com/jobseek/speedjobs/dto/resume/ResumeResponse.java
Labels: front

#143 fix: 검색태그 디자인 수정
  front/src/components/components/RecruitAdd/AnnouncementInfo.js
  front/src/components/components/Styled.js
  front/src/components/components/Tags.js
  front/src/components/pages/Community.js
  front/src/components/pages/Recruitment.js
  front/src/components/pages/RecruitmentDetail.js
  src/main/resources/http/post.http
  src/main/resources/http/recruit.http
Labels: front

#144 fix: 공고추가 페이지에서 사진추가 로직 수정
  front/src/components/components/RecruitAdd/AnnouncementInfo.js
  front/src/components/components/ResumeItem.js
  front/src/components/components/SubmitItem.js
  front/src/components/pages/Community.js
  front/src/components/pages/SubmitList.js
Labels: front

#152 Fix_지원된 이력서목록 모바일 레이아웃 수정
  front/src/components/components/ResumeItem.js
  front/src/components/components/SubmitItem.js
  front/src/components/pages/ResumeDetails.js
Labels: front

#155 feat: 배너 캐시 적용
  front/src/components/pages/RecruitmentDetail.js
  src/main/java/com/jobseek/speedjobs/common/file/dto/File.java
  src/main/java/com/jobseek/speedjobs/dto/banner/BannerResponse.java
  src/main/java/com/jobseek/speedjobs/dto/banner/BannerResponses.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagMap.java
  src/main/java/com/jobseek/speedjobs/dto/tag/TagResponses.java
  src/main/java/com/jobseek/speedjobs/service/BannerService.java
Labels: back

#158 fix: 공고 thumbnail 로직 수정
  front/src/components/components/Post.js
  front/src/components/components/img/img22.png
  front/src/components/components/img/jobseekLogo.png
  front/src/components/components/img/ridi.png
  front/src/components/pages/home/AnnounceCard.js
Labels: front

#161 fix: 스케쥴러 수정
  src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java
  src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
  src/main/java/com/jobseek/speedjobs/service/RecruitService.java
Labels: back
